### ISSUE TITLE
Install on seperate machine

### ISSUE THREAD

**Issue by TheLion** [adroste/3cx-tools#1]
Hi,

Do I install these tools on a seperate machine? Or on the 3CX box itself?

I was confused about the "Forward your 3CX ports to your dev machine" text in the last step. And I don't want to break my 3CX ;-)

**Comment by adroste** [comment]
It's intended to run on the same machine as 3CX. Currently only Debian/Raspberry Pi instances are supported.
However, I'm still working on it. Certain features like custom dial codes are not yet ready. 
But I am happy about additional support.

> And I don't want to break my 3CX ;-)

I don't want to break it, too. A short introduction on how the tools integrate:
1. Postgres Access (Internal 3CX DB): I don't want to mess with the DB, so only reading will happen, **no writes**. 
2. REST API (Management console): The management console frontend uses an internal REST API. I reverse engineered some endpoints. Using these endpoints is absolutely safe as it's the same as doing stuff on the management console frontend.
3. File watchers: Most of the magic is happening by watching 3CX file directories. E.g. when the phonebook changes, the watcher detects a write to the xml for the device phonebooks and "adds" the missing numbers (like home or business).

### Dev help appreciated

If you wan't to develop own features, add stuff, fix something just do it. I'm open for pull requests.
The structure is self explaining. The root is a nodejs (typescript) service (just look at the files). Additionally there are (for now) two sub-projects with frontend plugins (one for the webclient and for the management console) written in JS/React.

**Comment by TheLion** [comment]
> It's intended to run on the same machine as 3CX. Currently only Debian/Raspberry Pi instances are supported. However, I'm still working on it. Certain features like custom dial codes are not yet ready. But I am happy about additional support.

I have got it working. Works great. Running on the same RPi as 3CX.

I did notice some of the numbers got swapped on my Yealink W60B.

In 3CX a specific contact with 3 numbers looks like this:

![image](https://user-images.githubusercontent.com/3755011/147833118-581644a4-9221-4312-973b-c2741118c7bd.png)

On my Yealink it looks like this (hope you understand dutch, if not, let me translate, Kantoor means Office, Andere means Other):

![2021-12-31 17-53-17](https://user-images.githubusercontent.com/3755011/147833180-21eef231-f2fa-4f69-a653-7be4c32d4067.jpeg)

![2021-12-31 17-53-21](https://user-images.githubusercontent.com/3755011/147833190-c3585843-9023-4f92-886c-a64bc7c98062.jpeg)

Is there a way to swap some numbers around during the conversion, so they end up at the right place?

**Comment by adroste** [comment]
The yealink generator iterates over a predefined structure:
https://github.com/adroste/3cx-tools/blob/ec1c4c76b799d6e75f1418f62bacf2c969826aa4/src/func/phonebook-yealink.ts#L20

https://github.com/adroste/3cx-tools/blob/ec1c4c76b799d6e75f1418f62bacf2c969826aa4/src/func/phonebook.ts#L57-L70

So the display order is 'mobile', 'private', 'business' and then the secondary numbers 'mobile2', 'private2', 'business2'.

I'll make it adjustable. It's a simple change.

**Comment by adroste** [comment]
Done. It's now possible to customize the order.
Please add a file called `config.local.json` into the root folder (the same folder where the `config.default.json` is in).
Then set its content to:
```json
{
  "phoneNumberOrder": [
    "mobile",
    "mobile2",
    "private",
    "private2",
    "business",
    "business2",
    "extra"
  ]
}
```

Afterwards, restart the service (should be: `sudo systemctl restart 3cx-tools-service`). The phonebooks should regenerate now with the new config.

**Comment by TheLion** [comment]
Erh. Not quite. Only the mobile number is visible now. All the others has disappeared. And the mobile number is displayed as business. This is the case for all contacts.

I am not sure how the phone number fields are called in the database, but that's probably something you know ;-)

In the RAW XML there is also 1 number visible, mobile.
```
<DirectoryEntry>
    <Name>Monique Paulussen</Name>
    <Telephone>0610017887</Telephone>
</DirectoryEntry>
```

The yealink_phonebook.xml (in fact, all phonebooks are) is updated, as I see the date/time stamp change after I change a contact.

I pulled the latest GIT and restarted the service and also the whole Pi. Is there anything else I should do?

I did notice an error when quetying the status of the service.

```
Jan 01 19:12:37 3cx npm[21596]: [01.01.2022 19:12.37.161] [LOG]   [Dial Code API] listening for calls...
Jan 01 19:12:37 3cx npm[21596]: node:internal/process/promises:246
Jan 01 19:12:37 3cx npm[21596]:           triggerUncaughtException(err, true /* fromPromise */);
Jan 01 19:12:37 3cx npm[21596]:           ^
Jan 01 19:12:37 3cx npm[21596]: [Error: EACCES: permission denied, open '/var/lib/3cxpbx/Instance1/Data/Http/Interface/provisioning/0qlhnihf60youf/yealink_phonebook.xml'] {
Jan 01 19:12:37 3cx npm[21596]:   errno: -13,
Jan 01 19:12:37 3cx npm[21596]:   code: 'EACCES',
Jan 01 19:12:37 3cx npm[21596]:   syscall: 'open',
Jan 01 19:12:37 3cx npm[21596]:   path: '/var/lib/3cxpbx/Instance1/Data/Http/Interface/provisioning/0qlhnihf60youf/yealink_phonebook.xml'
```

The service seems to restart over and over again. I didn't notice this earlier before this pull.

Is there log somewhere I can look at?

**Comment by TheLion** [comment]
Already found it, was in syslog.

```
Jan  1 19:20:24 3cx systemd[1]: Started 3cx-tools-server - custom plugins, tools for 3CX.
Jan  1 19:20:25 3cx npm[26619]: > 3cx-tools-server@0.1.0 start
Jan  1 19:20:25 3cx npm[26619]: > NODE_ENV=production node build/src/main.js "run-as-service"
Jan  1 19:20:26 3cx npm[26619]:    _____ _______  __    ______            __
Jan  1 19:20:26 3cx npm[26619]:   |__  // ____/ |/ /   /_  __/___  ____  / /____
Jan  1 19:20:26 3cx npm[26619]:    /_ </ /    |   /     / / / __ \/ __ \/ / ___/
Jan  1 19:20:26 3cx npm[26619]:  ___/ / /___ /   |     / / / /_/ / /_/ / (__  )
Jan  1 19:20:26 3cx npm[26619]: /____/\____//_/|_|    /_/  \____/\____/_/____/
Jan  1 19:20:26 3cx npm[26619]: Service '3cx-tools-server' is: NOT ACTIVE
Jan  1 19:20:27 3cx npm[26619]: [01.01.2022 19:20.27.013] [LOG]   [Config loader] config loaded {
Jan  1 19:20:27 3cx npm[26619]:   ivrPromptsDir: '/var/lib/3cxpbx/Instance1/Data/Ivr/Prompts',
Jan  1 19:20:27 3cx npm[26619]:   pbxConfigJsonFile: '/var/lib/3cxpbx/Bin/config.json',
Jan  1 19:20:27 3cx npm[26619]:   provisioningDir: '/var/lib/3cxpbx/Instance1/Data/Http/Interface/provisioning',
Jan  1 19:20:27 3cx npm[26619]:   webclientDir: '/var/lib/3cxpbx/Data/Http/wwwroot/webclient',
Jan  1 19:20:27 3cx npm[26619]:   mcSettingsPanelBuildDir: '/home/pi/3cx-tools/mc-settings-panel/build/',
Jan  1 19:20:27 3cx npm[26619]:   nginxProxySnippetInstallFile: '/var/lib/3cxpbx/Bin/nginx/conf/snippets/14-3cx-tools-proxy.conf',
Jan  1 19:20:27 3cx npm[26619]:   serviceInstallFile: '/lib/systemd/system/3cx-tools-server.service',
Jan  1 19:20:27 3cx npm[26619]:   webclientCallOverviewPanelBuildDir: '/home/pi/3cx-tools/webclient-realtime-call-overview-panel/build/',
Jan  1 19:20:27 3cx npm[26619]:   activeCallsCheckIntervalMs: 500,
Jan  1 19:20:27 3cx npm[26619]:   dialCodes: {},
Jan  1 19:20:27 3cx npm[26619]:   httpPort: 4848,
Jan  1 19:20:27 3cx npm[26619]:   phoneNumberOrder: [
Jan  1 19:20:27 3cx npm[26619]:     'mobile',
Jan  1 19:20:27 3cx npm[26619]:     'mobile2',
Jan  1 19:20:27 3cx npm[26619]:     'private',
Jan  1 19:20:27 3cx npm[26619]:     'private2',
Jan  1 19:20:27 3cx npm[26619]:     'business',
Jan  1 19:20:27 3cx npm[26619]:     'business2',
Jan  1 19:20:27 3cx npm[26619]:     'extra'
Jan  1 19:20:27 3cx npm[26619]:   ]
Jan  1 19:20:27 3cx npm[26619]: }
Jan  1 19:20:27 3cx npm[26619]: [01.01.2022 19:20.27.024] [LOG]   running as service
Jan  1 19:20:27 3cx npm[26619]: [01.01.2022 19:20.27.029] [LOG]   [Nginx Proxy Snippet Installer] nginx proxy snippet already installed, skipping install
Jan  1 19:20:27 3cx npm[26619]: [01.01.2022 19:20.27.302] [LOG]   [3CX REST API] connected
Jan  1 19:20:27 3cx npm[26619]: [01.01.2022 19:20.27.366] [LOG]   [Phonebook Monitor] watching phonebook files...
Jan  1 19:20:27 3cx npm[26619]: [01.01.2022 19:20.27.368] [LOG]   [Caller ID] started
Jan  1 19:20:27 3cx npm[26619]: [01.01.2022 19:20.27.374] [LOG]   [Phonebook Yealink] patcher started
Jan  1 19:20:27 3cx npm[26619]: [01.01.2022 19:20.27.377] [LOG]   [Phonebook Fanvil] patcher started
Jan  1 19:20:27 3cx npm[26619]: [01.01.2022 19:20.27.381] [LOG]   [Phonebook Snom] patcher started
Jan  1 19:20:27 3cx npm[26619]: [01.01.2022 19:20.27.386] [LOG]   [Active Calls Monitor] started
Jan  1 19:20:27 3cx npm[26619]: [01.01.2022 19:20.27.388] [LOG]   [Call Log Monitor] started
Jan  1 19:20:27 3cx npm[26619]: [01.01.2022 19:20.27.404] [LOG]   [Web Server] HTTP server listening on port 4848
Jan  1 19:20:27 3cx npm[26619]: [01.01.2022 19:20.27.410] [LOG]   [Websocket API] WS api listening...
Jan  1 19:20:27 3cx npm[26619]: [01.01.2022 19:20.27.412] [LOG]   [Dial Code API] listening for calls...
Jan  1 19:20:27 3cx npm[26619]: node:internal/process/promises:246
Jan  1 19:20:27 3cx npm[26619]:           triggerUncaughtException(err, true /* fromPromise */);
Jan  1 19:20:27 3cx npm[26619]:           ^
Jan  1 19:20:27 3cx npm[26619]: [Error: EACCES: permission denied, open '/var/lib/3cxpbx/Instance1/Data/Http/Interface/provisioning/0qlhnihf60youf/yealink_phonebook.xml'] {
Jan  1 19:20:27 3cx npm[26619]:   errno: -13,
Jan  1 19:20:27 3cx npm[26619]:   code: 'EACCES',
Jan  1 19:20:27 3cx npm[26619]:   syscall: 'open',
Jan  1 19:20:27 3cx npm[26619]:   path: '/var/lib/3cxpbx/Instance1/Data/Http/Interface/provisioning/0qlhnihf60youf/yealink_phonebook.xml'
Jan  1 19:20:27 3cx npm[26619]: }
Jan  1 19:20:27 3cx systemd[1]: 3cx-tools-server.service: Main process exited, code=exited, status=1/FAILURE
Jan  1 19:20:27 3cx systemd[1]: 3cx-tools-server.service: Failed with result 'exit-code'.
```

**Comment by adroste** [comment]
`Permission denied` sounds like that the service was not able to write the phonebooks because it was not run as root.
Did you make `root` the owner of the 3cx-tools folder as described in the install steps?
```bash
cd 3cx-tools
sudo chown root .
```

It should look like this (root must be the name in the third column, the name in the fourth column does not matter):
```
root@vm3cx:~/3cx-tools# ls -al
total 564
drwxr-xr-x   8 root root   4096 Dec 30 13:16 .
drwx------   6 root root   4096 Dec 30 15:36 ..
-rw-r--r--   1 root root   1073 Dec 30 13:16 LICENSE
-rw-r--r--   1 root root   1832 Dec 30 13:16 README.md
drwxr-xr-x   3 root root   4096 Dec 25 21:41 build
-rw-r--r--   1 root root    674 Dec 30 13:16 config.default.json
-rw-r--r--   1 root root    351 Dec 30 13:16 config.dev.json
-rw-r--r--   1 root root    162 Dec 30 13:16 config.local.json
drwxr-xr-x   7 root root   4096 Dec 30 13:16 dev-resources
-rwxr-xr-x   1 root root    199 Dec 30 13:16 jest.config.js
drwxr-xr-x   5 root root   4096 Dec 30 13:16 mc-settings-panel
drwxr-xr-x 459 root root  20480 Dec 29 16:18 node_modules
-rw-r--r--   1 root root 488181 Dec 30 13:16 package-lock.json
-rw-r--r--   1 root root   2061 Dec 30 13:16 package.json
drwxr-xr-x   6 root root   4096 Dec 30 13:16 src
-rw-r--r--   1 root root    168 Dec 30 13:16 tsconfig.eslint.json
-rwxr-xr-x   1 root root    636 Dec 30 13:16 tsconfig.json
drwxr-xr-x   6 root root   4096 Dec 30 13:16 webclient-realtime-call-overview-panel
```

The reason that this is necessary is that npm will run the application as the user who owns the directory/files. And since we tinker with files that are owned by e.g. the phonesystem we need elevated rights.

**Comment by TheLion** [comment]
Yes, I did, Just did it again to be sure. Looks like this:

```
total 584
384003   4 drwxr-xr-x   8 root root   4096 Jan  1 18:40 .
   918   4 drwxr-xr-x   7 pi   pi     4096 Dec 30 13:27 ..
770259   4 drwxr-xr-x   3 root root   4096 Dec 30 13:27 build
385023   4 -rw-r--r--   1 root root    808 Jan  1 19:11 config.default.json
386158   4 -rw-r--r--   1 root root    351 Dec 30 13:27 config.dev.json
385017   4 -rw-r--r--   1 root root    137 Jan  1 19:11 config.local.json
386144   4 -rwxr-xr-x   1 root root    247 Dec 30 13:27 .editorconfig
386151   4 -rwxr-xr-x   1 root root      9 Dec 30 13:27 .eslintignore
386152   4 -rwxr-xr-x   1 root root    509 Dec 30 13:27 .eslintrc.js
770232   4 drwxr-xr-x   8 root root   4096 Jan  1 19:22 .git
386153   4 -rwxr-xr-x   1 root root    272 Dec 30 13:27 .gitignore
386159   4 -rwxr-xr-x   1 root root    199 Dec 30 13:27 jest.config.js
386155   4 -rw-r--r--   1 root root   1073 Dec 30 13:27 LICENSE
770339   4 drwxr-xr-x   5 root root   4096 Dec 30 13:27 mc-settings-panel
770496  20 drwxr-xr-x 117 root root  20480 Dec 30 13:27 node_modules
386161   4 -rw-r--r--   1 root root   2061 Dec 30 13:27 package.json
386160 480 -rw-r--r--   1 root root 488181 Dec 30 13:27 package-lock.json
386154   4 -rwxr-xr-x   1 root root    167 Dec 30 13:27 .prettierrc
386156   4 -rw-r--r--   1 root root   1832 Dec 30 13:27 README.md
386162   4 drwxr-xr-x   6 root root   4096 Jan  1 18:40 src
386171   4 -rw-r--r--   1 root root    168 Dec 30 13:27 tsconfig.eslint.json
386172   4 -rwxr-xr-x   1 root root    636 Dec 30 13:27 tsconfig.json
770424   4 drwxr-xr-x   5 root root   4096 Dec 30 13:27 webclient-realtime-call-overview-panel
```

Still an error though, but a different one

```
Jan  1 20:35:29 3cx systemd[1]: Started 3cx-tools-server - custom plugins, tools for 3CX.
Jan  1 20:35:31 3cx npm[3665]: > 3cx-tools-server@0.1.0 start
Jan  1 20:35:31 3cx npm[3665]: > NODE_ENV=production node build/src/main.js "run-as-service"
Jan  1 20:35:32 3cx npm[3665]:    _____ _______  __    ______            __
Jan  1 20:35:32 3cx npm[3665]:   |__  // ____/ |/ /   /_  __/___  ____  / /____
Jan  1 20:35:32 3cx npm[3665]:    /_ </ /    |   /     / / / __ \/ __ \/ / ___/
Jan  1 20:35:32 3cx npm[3665]:  ___/ / /___ /   |     / / / /_/ / /_/ / (__  )
Jan  1 20:35:32 3cx npm[3665]: /____/\____//_/|_|    /_/  \____/\____/_/____/
Jan  1 20:35:32 3cx npm[3665]: Service '3cx-tools-server' is: NOT ACTIVE
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.157] [LOG]   [Config loader] config loaded {
Jan  1 20:35:32 3cx npm[3665]:   ivrPromptsDir: '/var/lib/3cxpbx/Instance1/Data/Ivr/Prompts',
Jan  1 20:35:32 3cx npm[3665]:   pbxConfigJsonFile: '/var/lib/3cxpbx/Bin/config.json',
Jan  1 20:35:32 3cx npm[3665]:   provisioningDir: '/var/lib/3cxpbx/Instance1/Data/Http/Interface/provisioning',
Jan  1 20:35:32 3cx npm[3665]:   webclientDir: '/var/lib/3cxpbx/Data/Http/wwwroot/webclient',
Jan  1 20:35:32 3cx npm[3665]:   mcSettingsPanelBuildDir: '/home/pi/3cx-tools/mc-settings-panel/build/',
Jan  1 20:35:32 3cx npm[3665]:   nginxProxySnippetInstallFile: '/var/lib/3cxpbx/Bin/nginx/conf/snippets/14-3cx-tools-proxy.conf',
Jan  1 20:35:32 3cx npm[3665]:   serviceInstallFile: '/lib/systemd/system/3cx-tools-server.service',
Jan  1 20:35:32 3cx npm[3665]:   webclientCallOverviewPanelBuildDir: '/home/pi/3cx-tools/webclient-realtime-call-overview-panel/build/',
Jan  1 20:35:32 3cx npm[3665]:   activeCallsCheckIntervalMs: 500,
Jan  1 20:35:32 3cx npm[3665]:   dialCodes: {},
Jan  1 20:35:32 3cx npm[3665]:   httpPort: 4848,
Jan  1 20:35:32 3cx npm[3665]:   phoneNumberOrder: [
Jan  1 20:35:32 3cx npm[3665]:     'mobile',
Jan  1 20:35:32 3cx npm[3665]:     'mobile2',
Jan  1 20:35:32 3cx npm[3665]:     'private',
Jan  1 20:35:32 3cx npm[3665]:     'private2',
Jan  1 20:35:32 3cx npm[3665]:     'business',
Jan  1 20:35:32 3cx npm[3665]:     'business2',
Jan  1 20:35:32 3cx npm[3665]:     'extra'
Jan  1 20:35:32 3cx npm[3665]:   ]
Jan  1 20:35:32 3cx npm[3665]: }
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.166] [LOG]   running as service
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.170] [LOG]   [Nginx Proxy Snippet Installer] nginx proxy snippet already installed, skipping install
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.428] [LOG]   [3CX REST API] connected
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.493] [LOG]   [Phonebook Monitor] watching phonebook files...
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.495] [LOG]   [Caller ID] started
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.501] [LOG]   [Phonebook Yealink] patcher started
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.506] [LOG]   [Phonebook Fanvil] patcher started
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.510] [LOG]   [Phonebook Snom] patcher started
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.515] [LOG]   [Active Calls Monitor] started
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.518] [LOG]   [Call Log Monitor] started
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.533] [LOG]   [Web Server] HTTP server listening on port 4848
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.541] [LOG]   [Websocket API] WS api listening...
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.543] [LOG]   [Dial Code API] listening for calls...
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.658] [LOG]   [Phonebook Yealink] yealink phonebook updated
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.659] [LOG]   [Phonebook Fanvil] fanvil phonebook updated
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.660] [LOG]   [Phonebook Snom] snom phonebook updated
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.663] [LOG]   [Call Overview Panel] installed
Jan  1 20:35:32 3cx npm[3665]: [01.01.2022 20:35.32.664] [LOG]   [Call Overview Panel] watching for file modifications...
Jan  1 20:35:32 3cx npm[3665]: /home/pi/3cx-tools/build/src/func/call-logs.js:134
Jan  1 20:35:32 3cx npm[3665]:             let extCaller = segments[0].direction === 'incoming'
Jan  1 20:35:32 3cx npm[3665]:                                     ^
Jan  1 20:35:32 3cx npm[3665]: TypeError: Cannot read properties of undefined (reading '0')
Jan  1 20:35:32 3cx npm[3665]:     at /home/pi/3cx-tools/build/src/func/call-logs.js:134:37
Jan  1 20:35:32 3cx npm[3665]:     at Array.map (<anonymous>)
Jan  1 20:35:32 3cx npm[3665]:     at /home/pi/3cx-tools/build/src/func/call-logs.js:131:32
Jan  1 20:35:32 3cx npm[3665]:     at Generator.next (<anonymous>)
Jan  1 20:35:32 3cx npm[3665]:     at fulfilled (/home/pi/3cx-tools/node_modules/tslib/tslib.js:114:62)
Jan  1 20:35:32 3cx npm[3665]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Jan  1 20:35:32 3cx systemd[1]: 3cx-tools-server.service: Main process exited, code=exited, status=1/FAILURE
Jan  1 20:35:32 3cx systemd[1]: 3cx-tools-server.service: Failed with result 'exit-code'.
```

There is more info in the Yealink Phonebook, but the order is not correct yet. It lists as Business. Mobile, Other. As the order in the XML correspond with should be Mobile, Mobile2, Home, according to the names in 3CX and the numbers shown.

And I noticed there is also an order listed for the phonenumber in the `config.default.json`.

**Comment by adroste** [comment]
Yes. Every key you define inside the `config.local.json` will override existing conf from the `config.default.json`.
Please check that the entries (`<Telephone>xxx</Telephone>`) inside the xml are in the correct order (on your machine: `/var/lib/3cxpbx/Instance1/Data/Http/Interface/provisioning/0qlhnihf60youf/yealink_phonebook.xml`).

About the other error. Really weird that you seem to have calls without segments. This is not the case for me. At least not for the both 3cx instances I have. I'll add a check to skip call logs for calls without segments... You are using v18 right?

**Comment by TheLion** [comment]
Great. The service keeps running now.

But there is an error in the log about segments

```
Jan  1 22:58:06 3cx npm[15198]: > 3cx-tools-server@0.1.0 start
Jan  1 22:58:06 3cx npm[15198]: > NODE_ENV=production node build/src/main.js "run-as-service"
Jan  1 22:58:07 3cx npm[15198]:    _____ _______  __    ______            __
Jan  1 22:58:07 3cx npm[15198]:   |__  // ____/ |/ /   /_  __/___  ____  / /____
Jan  1 22:58:07 3cx npm[15198]:    /_ </ /    |   /     / / / __ \/ __ \/ / ___/
Jan  1 22:58:07 3cx npm[15198]:  ___/ / /___ /   |     / / / /_/ / /_/ / (__  )
Jan  1 22:58:07 3cx npm[15198]: /____/\____//_/|_|    /_/  \____/\____/_/____/
Jan  1 22:58:07 3cx npm[15198]: Service '3cx-tools-server' is: NOT ACTIVE
Jan  1 22:58:07 3cx npm[15198]: [01.01.2022 22:58.07.773] [LOG]   [Config loader] config loaded {
Jan  1 22:58:07 3cx npm[15198]:   ivrPromptsDir: '/var/lib/3cxpbx/Instance1/Data/Ivr/Prompts',
Jan  1 22:58:07 3cx npm[15198]:   pbxConfigJsonFile: '/var/lib/3cxpbx/Bin/config.json',
Jan  1 22:58:07 3cx npm[15198]:   provisioningDir: '/var/lib/3cxpbx/Instance1/Data/Http/Interface/provisioning',
Jan  1 22:58:07 3cx npm[15198]:   webclientDir: '/var/lib/3cxpbx/Data/Http/wwwroot/webclient',
Jan  1 22:58:07 3cx npm[15198]:   mcSettingsPanelBuildDir: '/home/pi/3cx-tools/mc-settings-panel/build/',
Jan  1 22:58:07 3cx npm[15198]:   nginxProxySnippetInstallFile: '/var/lib/3cxpbx/Bin/nginx/conf/snippets/14-3cx-tools-proxy.conf',
Jan  1 22:58:07 3cx npm[15198]:   serviceInstallFile: '/lib/systemd/system/3cx-tools-server.service',
Jan  1 22:58:07 3cx npm[15198]:   webclientCallOverviewPanelBuildDir: '/home/pi/3cx-tools/webclient-realtime-call-overview-panel/build/',
Jan  1 22:58:07 3cx npm[15198]:   activeCallsCheckIntervalMs: 500,
Jan  1 22:58:07 3cx npm[15198]:   dialCodes: {},
Jan  1 22:58:07 3cx npm[15198]:   httpPort: 4848,
Jan  1 22:58:07 3cx npm[15198]:   phoneNumberOrder: [
Jan  1 22:58:07 3cx npm[15198]:     'mobile',
Jan  1 22:58:07 3cx npm[15198]:     'mobile2',
Jan  1 22:58:07 3cx npm[15198]:     'private',
Jan  1 22:58:07 3cx npm[15198]:     'private2',
Jan  1 22:58:07 3cx npm[15198]:     'business',
Jan  1 22:58:07 3cx npm[15198]:     'business2',
Jan  1 22:58:07 3cx npm[15198]:     'extra'
Jan  1 22:58:07 3cx npm[15198]:   ]
Jan  1 22:58:07 3cx npm[15198]: }
Jan  1 22:58:07 3cx npm[15198]: [01.01.2022 22:58.07.782] [LOG]   running as service
Jan  1 22:58:07 3cx npm[15198]: [01.01.2022 22:58.07.788] [LOG]   [Nginx Proxy Snippet Installer] nginx proxy snippet already installed, skipping install
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.072] [LOG]   [3CX REST API] connected
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.138] [LOG]   [Phonebook Monitor] watching phonebook files...
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.139] [LOG]   [Caller ID] started
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.146] [LOG]   [Phonebook Yealink] patcher started
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.151] [LOG]   [Phonebook Fanvil] patcher started
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.155] [LOG]   [Phonebook Snom] patcher started
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.160] [LOG]   [Active Calls Monitor] started
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.163] [LOG]   [Call Log Monitor] started
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.180] [LOG]   [Web Server] HTTP server listening on port 4848
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.187] [LOG]   [Websocket API] WS api listening...
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.188] [LOG]   [Dial Code API] listening for calls...
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.304] [LOG]   [Phonebook Yealink] yealink phonebook updated
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.305] [LOG]   [Phonebook Fanvil] fanvil phonebook updated
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.307] [LOG]   [Call Overview Panel] installed
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.308] [LOG]   [Call Overview Panel] watching for file modifications...
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.310] [LOG]   [Phonebook Snom] snom phonebook updated
Jan  1 22:58:08 3cx npm[15198]: [01.01.2022 22:58.08.378] [ERROR] [Call Log Monitor] segments is undefined. call: {
Jan  1 22:58:08 3cx npm[15198]:   id: 1224,
Jan  1 22:58:08 3cx npm[15198]:   start_time: 2021-12-28T11:47:29.000Z,
Jan  1 22:58:08 3cx npm[15198]:   end_time: 2021-12-28T11:47:29.000Z,
Jan  1 22:58:08 3cx npm[15198]:   is_answered: false,
Jan  1 22:58:08 3cx npm[15198]:   ringing_dur: null,
Jan  1 22:58:08 3cx npm[15198]:   talking_dur: null,
Jan  1 22:58:08 3cx npm[15198]:   q_wait_dur: null
Jan  1 22:58:08 3cx npm[15198]: }
Jan  1 22:58:11 3cx npm[15198]: [01.01.2022 22:58.11.319] [LOG]   [Phonebook Yealink] yealink phonebook updated
Jan  1 22:58:11 3cx npm[15198]: [01.01.2022 22:58.11.320] [LOG]   [Phonebook Fanvil] fanvil phonebook updated
Jan  1 22:58:11 3cx npm[15198]: [01.01.2022 22:58.11.321] [LOG]   [Phonebook Snom] snom phonebook updated
```
I found out why the W60B doesn't display the correct names with the numbers. I downloaded a template from the base station and that only lists "OfficeNumber","MobileNumber","OtherNumber", in that order. Also, when I try to create a new contact in the address book on the phone itself, it only has these options. So there aren't anymore, probably.

So, I will use OfficeNumber (Yealink) for Private (3CX), MobileNumber (Yealink) for Mobile (3CX), and OtherNumber (Yealink) for Mobile2 (3CX). This should be the order, right?

```
{
  "phoneNumberOrder": [
    "private",
    "mobile",
    "mobile2",
    "extra",
    "private2",
    "business",
    "business2"
}
```

Doesn't change with it though, unfortunately :-(
Seems like whatever I choose as order, it doesn't change.

**Comment by adroste** [comment]
Make sure to restart the service after every change to local config (`sudo systemctl restart 3cx-tools-service`).
Could also be reasonable to restart the phone to circumvent the phone to cache old views.

I know someone with a W60B and two W56H. Maybe I am able to test this myself...

About the error: ignore it. Seems like everything is okay. You just had one call with id: 1224 in the past which seems to have an incomplete log entry. Maybe your instance was interrupted before the call log could be written completely.

---

However, I'm really disappointed with all of my 3CX instances. I'm seriously considering switching to FreePBX. Even simple features like distinctive ringtones per line are just not possible with 3CX.
FreePBX on the other hand lacks a proper contact management, callerId lookup as well as call panel.
But as I'm also not happy with what 3CX provides for home/small businesses I think I'll have to build a simple panel myself (FOP2 / iSymphony are also really bad).

**Comment by TheLion** [comment]
> Make sure to restart the service after every change to local config (`sudo systemctl restart 3cx-tools-service`). Could also be reasonable to restart the phone to circumvent the phone to cache old views.

I restart the service every time I change something. And I look at the XML directly with the webbrowser, not on the phone.

> I know someone with a W60B and two W56H. Maybe I am able to test this myself...

That would be helpfull and faster/easier to troubleshoot for sure ;-)

> However, I'm really disappointed with all of my 3CX instances. I'm seriously considering switching to FreePBX. Even simple features like distinctive ringtones per line are just not possible with 3CX. FreePBX on the other hand lacks a proper contact management, callerId lookup as well as call panel. But as I'm also not happy with what 3CX provides for home/small businesses I think I'll have to build a simple panel myself (FOP2 / iSymphony are also really bad).

Hmmm. I use it (free version) at home and it does what it should for home use. Will take a look at FreePBX though, always looking for something different/better/easier ;-)

**Comment by adroste** [comment]
Hey @TheLion I was not able to test the order "problem" on the yealink phones yet, but the general caching problem could be solved by lowering the refresh time inside the admin panel of the dect bridge.
Please see the new Readme hint. I don't intend to develop any further for 3CX as I switched to FreePBX. But I migrated the phonebook generation to FreePBX and also massively improved the panel itself.
Please look at: https://github.com/adroste/freepbx-realtime-calls-contacts-panel
